server:
  port: 8082

spring:
  mvc:
    view:
      prefix: /
      suffix: .html

# 设置nacos的地址（配置中心）
nacos:
  discovery:
    server-addr: 127.0.0.1:8848

# Dubbo 广播方式配置，如果调用不稳定可以修改为直连模式：https://codechina.csdn.net/KnowledgePlanet/Lottery/-/issues/1
dubbo:
  application:
    name: Lucky-ERP
    version: 1.0.0
  registry:
#    address: N/A
#    address: #multicast://224.5.6.7:1234
#    address: zookeeper://127.0.0.1:2181
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: -1